import{S as w,i}from"./assets/vendor-BrddEoy-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const v="53613119-f2730f8cf542fb1098fca49a3",E="https://pixabay.com/api/",$=15;async function p(o,e=1){const r=`${E}?key=${v}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&per_page=${$}&page=${e}`,a=await fetch(r);if(!a.ok)throw new Error("Ошибка при загрузке изображений");return await a.json()}const m=document.querySelector("#gallery"),y=document.querySelector("#loader"),h=document.querySelector("#load-more"),P=new w(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",e),P.refresh()}function S(){m.innerHTML=""}function L(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const B=document.querySelector("#search-form");let c="",n=1,f=0;B.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!!c){n=1,S(),l(),L();try{const e=await p(c,n);if(e.hits.length===0){i.error({title:"No results",message:"No images found."}),u();return}g(e.hits),f=e.totalHits,n*15<f?b():(l(),i.info({title:"End",message:"You've reached the end of search results."}))}catch(e){i.error({title:"Error",message:e.message})}finally{u()}}});h.addEventListener("click",async()=>{n+=1,l(),L();try{const o=await p(c,n);g(o.hits);const e=m.firstElementChild;if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}n*15<f?b():(l(),i.info({title:"End",message:"You've reached the end of search results."}))}catch(o){i.error({title:"Error",message:o.message})}finally{u()}});
//# sourceMappingURL=index.js.map
